### ISSUE TITLE
Codes

### ISSUE THREAD

**Issue by A11en0** [minnesotanlp/p2c#1]
Hi, thanks for your great job. could you please share the codes and model?

**Comment by dykang** [comment]
@bbuing9 can you help on this?

**Comment by bbuing9** [comment]
Thanks for your interest in our work!  Also, I'm sorry for the delay of sharing the codes and models, due to my preparation and movement for post-doc. 

Now, I'm working on re-factoring the codes along with the models and datasets, and I'll release them within 1-2 weeks. At that time, I'll let you know!

**Comment by bbuing9** [comment]
Finally, all the materials (codes, dataset, and pre-trained weights) are updated. Please check this, @A11en0.
